// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetAddressesData, GetAddressesError, GetAddressesResponse, GetValidateData, GetValidateError, GetValidateResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * List addresses by query parameters.
 * List addresses.
 */
export const getAddresses = <ThrowOnError extends boolean = false>(options?: Options<GetAddressesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAddressesResponse, GetAddressesError, ThrowOnError>({
        ...options,
        security: [
            {
                fn: 'apiKey',
                in: 'header',
                name: 'Authorization'
            }
        ],
        url: '/addresses'
    });
};

/**
 * Validate an address by query parameters.
 * Validate an address.
 */
export const getValidate = <ThrowOnError extends boolean = false>(options: Options<GetValidateData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetValidateResponse, GetValidateError, ThrowOnError>({
        ...options,
        security: [
            {
                fn: 'apiKey',
                in: 'header',
                name: 'Authorization'
            }
        ],
        url: '/validate'
    });
};