name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: myparcelnl/actions/pnpm-install@v4
        with:
          node-version: '22.x'

      - uses: ./.github/actions/build
