name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - uses: myparcelnl/actions/pnpm-install@v5
        with:
          node-version: '22.x'

      - uses: ./.github/actions/build
