name: Run pull request checks

on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.number }}'
  cancel-in-progress: true

jobs:
    lint:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v4

        - uses: myparcelnl/actions/pnpm-install@v5
          with:
            node-version: '22.x'

        - run: pnpm run lint

    build:
        needs: lint
        uses: ./.github/workflows/build.yml
        secrets: inherit

    test:
        needs:
        - lint
        - build
        uses: ./.github/workflows/test.yml
        secrets: inherit

    notify-on-failure:
        needs:
        - lint
        - build
        - test
        if: always() && contains(needs.*.result, 'failure')
        uses: myparcelnl/actions/.github/workflows/notify-on-failure.yml@v5
        secrets: inherit