name: 'Release new version 🚀'

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Skip checking for new commits and run all jobs'
        type: 'boolean'

  schedule:
    - cron: '0 * * * *'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-22.04
    outputs:
      has-refs: ${{ steps.has-refs.outputs.has-refs }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: myparcelnl/actions/has-refs-between@v5
        id: has-refs

  test:
    needs: prepare
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    runs-on: ubuntu-22.04
    needs:
      - prepare
      - test
    steps:
      - uses: myparcelnl/actions/setup-git-credentials@v5
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.credentials.outputs.token }}
          fetch-depth: 0

      - uses: myparcelnl/actions/pnpm-install@v5
        with:
          node-version: '22.x'

      - uses: ./.github/actions/build

      - name: 'Release'
        uses: myparcelnl/actions/semantic-release@v5
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          token: ${{ steps.credentials.outputs.token }}

  rebase-prs:
    needs: release
    uses: ./.github/workflows/rebase-prs.yml
    secrets: inherit

  notify-on-failure:
    needs:
      - test
      - release
      - rebase-prs
    if: always() && contains(needs.*.result, 'failure')
    uses: myparcelnl/actions/.github/workflows/notify-on-failure.yml@v5
    secrets: inherit
