name: Run tests

on:
  workflow_call:

jobs:
  test:
    name: 'Run unit tests'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: myparcelnl/actions/pnpm-install@v4
        with:
          node-version: '22.x'

      - run: pnpm run test:coverage
