name: Run tests

on:
  workflow_call:

jobs:
  test:
    name: 'Run unit tests'
    runs-on: ubuntu-22.04
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - uses: myparcelnl/actions/pnpm-install@v5
        with:
          node-version: '22.x'

      - run: pnpm run test:coverage
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

      - name: 'Report Coverage'
        # Set if: always() to also generate the report if tests are failing
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
